# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a21da3498bef7d86baf061718a0aba553f0a6140603325b33e51a76035aba76cf19e974142e8539a6100586b9951f1c78df2c59872ff329b359f7043c94c3067

test:
  secret_key_base: c6de8e31ebc813e3cd0eaca35f1de3004501d4da8258dc13c16a0a148895b5bf13f101438cb9cb35ce4ee1346a71aafeb71da2353830ec9ea1ec7e6442a07b16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
